### ISSUE TITLE
Index out of bounds issue

### ISSUE THREAD

**Issue by tyczj** [vgrichina/ios-calendar#9]
when trying to run your code from the demo project I get a NSRangeException error that goes back into the CXCalendarView.m class in the cellForDate.

if I comment out the if statement in there it runs but the month shows null on the first run. When i go to a different month then go back it displays fine

**Comment by ParthaGudivada** [comment]
It is because the calendar object needs to be instantiated  before setting the values for selectedDate and displayedDate.  

```
Replace the content of the initWithFrame method with the following :
```
- (id) initWithFrame: (CGRect) frame {
  if ((self = [super initWithFrame: frame])) {
      self.backgroundColor = [UIColor clearColor];
  
  ```
  _monthBarHeight = 48;
  _weekBarHeight = 32;
  
  _dateFormatter = [NSDateFormatter new];
  _dateFormatter.locale = [NSLocale autoupdatingCurrentLocale];
  _calendar = [[NSCalendar currentCalendar] retain];
  
  self.selectedDate = nil;
  self.displayedDate = [NSDate date];
  ```
  
  }
  
  return self;
  }
  
  everything works fine..  Hope this helps.

**Comment by vgrichina** [comment]
Fixed this
